apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-azurevote-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
        app: {{ .Release.Name }}-azure-vote-back
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
