kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-azurevote-front-svc
spec:
  selector:
    app:  {{ .Release.Name }}-azure-vote-front
  type:  LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort:  http
